### ISSUE TITLE
Feature request - put in an example of how to use Tuple in docs

### ISSUE THREAD

**Issue by codekiln** [lidatong/dataclasses-json#313] opened 2021-09-09 18:36 UTC
How should we use `typing.Tuple`? Here's an ipython session illustrating the problem: 

```
In [1]: from dataclasses_json import DataClassJsonMixin
In [2]: from dataclasses import dataclass

In [3]: @dataclass
    ...: class Foo(DataClassJsonMixin):
    ...:     bar: Tuple[Optional[float]]
    ...:

In [4]: Foo.schema()
ValueError: tuple_fields must be an iterable of Field classes or instances.

In [5]: @dataclass
    ...: class Foo(DataClassJsonMixin):
    ...:     bar: Tuple[Optional[float], Optional[float]]
    ...:

In [6]: Foo.schema()
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by george-zubrienko** [comment] 2023-07-20 22:22
Duplicate of #318 - known issue with marshmallow

**Closed** 2023-07-20 22:22 UTC

**Comment by matt035343** [comment] 2023-07-25 13:31
This is fixed by https://github.com/lidatong/dataclasses-json/issues/432 / https://github.com/lidatong/dataclasses-json/pull/434.
