### ISSUE TITLE
AttributeError: type object 'str' has no attribute '__args__'

### ISSUE THREAD

**Issue by hasanatkazmi** [lidatong/dataclasses-json#13] opened 2018-09-11 06:39 UTC
I have a very small snippet: 
```
@dataclass_json
@dataclass
class Test:
    entry: List[str]

t = Test(entry=[])
t.entry.append('mytest')
t = Test.from_json(t.to_json())
```
but even this is failing with this traceback:
```
  File "dc.py", line 25, in <module>
    t = Test.from_json(t.to_json())
  File "/private/tmp/testdc/env/lib/python3.7/site-packages/dataclasses_json/api.py", line 62, in from_json
    return _decode_dataclass(cls, init_kwargs, infer_missing)
  File "/private/tmp/testdc/env/lib/python3.7/site-packages/dataclasses_json/core.py", line 47, in _decode_dataclass
    infer_missing)
  File "/private/tmp/testdc/env/lib/python3.7/site-packages/dataclasses_json/core.py", line 83, in _decode_generic
    res = _get_type_cons(type_)(xs)
  File "/private/tmp/testdc/env/lib/python3.7/site-packages/dataclasses_json/core.py", line 77, in <genexpr>
    xs = (_decode_generic(type_arg, v, infer_missing) for v in value)
  File "/private/tmp/testdc/env/lib/python3.7/site-packages/dataclasses_json/core.py", line 73, in _decode_generic
    type_arg = type_.__args__[0]
AttributeError: type object 'str' has no attribute '__args__'
```
This issue might be duplicate of issue 2.

**Comment by lidatong** [comment] 2018-09-15 15:51
thanks for calling this out, and  you're right this is a duplicate of #12. thanks for the corresponding pr, fix in #16

**Closed by lidatong** 2018-09-15 15:51 UTC
