### ISSUE TITLE
TypeError: make_instance() got an unexpected keyword argument 'many'

### ISSUE THREAD

**Issue by kkbblzq** [lidatong/dataclasses-json#136] opened 2019-09-03 09:57 UTC
dataclasses-json==0.3.1
marshmallow==3.0.1
marshmallow-enum==1.5.1
python 3.7.3
'''
@dataclass_json
@dataclass
class Person:
    name: str
    age: int

if __name__ == '__main__':
    data = [{'name': 'zs', 'age': 1}, {'name': 'ls', 'age': 2}]
    Person.schema().load(data, many=True)
'''

raise TypeError 
TypeError: make_instance() got an unexpected keyword argument 'many'

**Comment by yukihiko-shinoda** [comment] 2019-09-03 13:50
Duplicate of #135

**Closed** 2019-09-04 01:01 UTC
